### ISSUE TITLE
Remove last remaining templates

### ISSUE THREAD

**Issue by deitch** [lf-edge/eve#2406]
Per #2353 and its linked offshoots, we have static hashes for _almost_ all of our Dockerfiles. These provide predictable and auditable builds, while changing only precisely what you want to change. You always _can_ take the latest git hash of _everything_, but it became a _choice_.

This issue is to track any remaining templates and decide how (and if) we want to approach them.

What is left?

The only places we still use the `*_TAG` stuff and generate things runtime from templates are:

- [ ] `pkg/eve/Dockerfile.in`
- [x] `images/docker-compose.yml.in`
- [ ] `images/rootfs.yml.in`

All of them can be updated the same as the others.

**Comment by rvs** [comment]
No, we're definitely not changing those. There @zededa-yuri comments very much apply and pain is high.

**Comment by deitch** [comment]
I am not 100% sure they do, or that the pain is high. Let's look at each in turn:

### pkg/eve/Dockerfile.in

```dockerfile
FROM MKISO_TAG as iso
FROM IPXE_TAG as ipxe
FROM MKRAW_TAG as raw
FROM MKCONF_TAG as conf
```

4 fairly infrequently changed source images, and all of them fit nicely within the "just run `update-component-sha.sh`" model (or even manually, if it is just one).

### images/docker-compose.yml.in

```yml
        image: STORAGE_INIT_TAG
        image: NEWLOGD_TAG
        image: WWAN_TAG
        image: WLAN_TAG
        image: GUACD_TAG
        image: VTPM_TAG
        image: WATCHDOG_TAG
        image: XENTOOLS_TAG
        image: KVMTOOLS_TAG
        image: PILLAR_TAG
```

This is just used to run things locally. It also fits pretty well within the workflow. 

* someone who downloads this and runs `make run-compose` should get the latest merged in and pushed out images, which "just works"
* someone who is working on changing those, should update the compose yml dependencies

My only real hesitation with this one is `PILLAR_TAG`. It really does change pretty often, which may very well lead to 2 people working at the same time in parallel, but in different parts of pillar that did not need to rebase after the first merges before, now needing to rebase, because they both affect this same one line in `docker-compose.yml`.

I believe that was one of the key issues that @zededa-yuri raised?

### images/rootfs.yml.in

```yml
  image: KERNEL_TAG
  - DOM0ZTOOLS_TAG
  - GRUB_TAG
  - FW_TAG
  - XEN_TAG
  - GPTTOOLS_TAG
     image: RNGD_TAG
     image: STORAGE_INIT_TAG
     image: NEWLOGD_TAG
     image: DEBUG_TAG
     image: WWAN_TAG
     image: WLAN_TAG
     image: GUACD_TAG
     image: PILLAR_TAG
     image: VTPM_TAG
     image: WATCHDOG_TAG
     image: XENTOOLS_TAG
```

Same as before. Every one of these except for one changes infrequently and just won't be an issue. `PILLAR_TAG` is the one that concerns me.

@zededa-yuri was that the correct issue?

**Comment by deitch** [comment]
Either way, I think it does advocate for doing `pkg/eve/Dockerfile.in`.

**Comment by rvs** [comment]
Almost forgot about this. @deitch my question is -- now that all the real Dockerfiles are done, what is the actual benefit of fixing the remaining 3 places? Note that those places are, in effect, how we assemble one final image -- these are not expected to be normal.

**Comment by deitch** [comment]
I still see the benefit, as anything that allows us to simplify the toolchain is a "good thing". I am going to stew over this over the next two days and see if I can come up with cleaner flows for these.

You know what the right answer is for `rootfs.yml.in`? `--build-arg` for linuxkit. If we did that, it wouldn't be a problem. I have raised it before, I always get pushback.

**Comment by deitch** [comment]
Going back through this. The absolute easiest win is the compose file. We easily could replace this:

```yml
services:
    # this is the only service from the onboot: section
    storage-init:
        image: STORAGE_INIT_TAG
        volumes:
            - persist:/persist
            - config:/config
            - type: bind
              source: CURDIR/conf
              target: /conf
            - type: bind
              source: CURDIR/pkg
              target: /pkg
        # network_mode: host
        networks:
            - eve
```

with this:

```yml
services:
    # this is the only service from the onboot: section
    storage-init:
        image: ${STORAGE_INIT_IMAGE}
        volumes:
            - persist:/persist
            - config:/config
            - type: bind
              source: CURDIR/conf
              target: /conf
            - type: bind
              source: CURDIR/pkg
              target: /pkg
        # network_mode: host
        networks:
            - eve
```

and then have the Makefile run it as:

```
docker-compose --env-file my-env-file -f images/docker-compose.yml up
```

Instead of generating the compose yml, we have a fully valid one at all times, and generate the images file. Allows us to use validation tools on the compose, yetus, etc. etc.

Even more, it is a file that will not need to change, yet be valid.

That leaves `rootfs.yml.in` and `eve/Dockerfile.in`. I have no easy answer for rootfs; linuxkit just doesn't support build-args. Dockerfile is easy, as it is just 4 infrequently changed dependencies.
